version: '3.8'

services:
  # Serviço da API
  app:
    # Constrói a imagem a partir do Dockerfile na raiz do projeto
    build: .
    # Comando para iniciar a aplicação FastAPI com Uvicorn
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    # Mapeia a porta 8000 do contêiner para a porta 8000 do host
    ports:
      - "8000:8000"
    # Define um volume para persistir o banco de dados SQLite
    volumes:
      - .:/app
